const UPDATE_TYPE = "game/UPDATE_TYPE";
const UPDATE_TOTAL_WIN = "game/UPDATE_TOTAL_WIN";
const UPDATE_TOTAL_GAME_PLAY = "game/UPDATE_TOTAL_GAME_PLAY";
const UPDATE_TOTAL_WHILE_PLAY = "game/UPDATE_TOTAL_WHILE_PLAY";
const PLAY_GAME = "game/PLAY_GAME";
export { UPDATE_TYPE, UPDATE_TOTAL_WIN, UPDATE_TOTAL_GAME_PLAY, UPDATE_TOTAL_WHILE_PLAY, PLAY_GAME }